### ISSUE TITLE
Missing config/database.yml

### ISSUE THREAD

**Issue by tosih** [FancyPixel/small-rails#1]
rake db:create spits out an error about a missing config/database.yml.

I notice it was ignored in your .gitignore, adding a this file worked for me. This is all new to me, but I hope this helps.
## config/database.yml

development:
  adapter: sqlite3
  database: db/development.sqlite3

**Comment by andreamazz** [comment]
Oops, you are right, I forgot to remove that entry from the gitingore. Thanks for the feedback, I'll fix it right away.
