### ISSUE TITLE
Trouble consuming API

### ISSUE THREAD

**Issue by Abundnce10** [FancyPixel/small-rails#3]
I cloned this repository and followed the commands in the README file.  However, when I go to make `curl` commands to create a user I'm having trouble.  Can you add example `curl` commands to the README so that people new to the repo know how to consume the API?

I ran `rake routes` and found a `POST` to `v1/users(.:format)` would hit the `users#create` method.  So, I try this command: `curl -X POST -H "Content-Type: application/json" -d '{"username": "testuser", "email": "test@example.com", "password": "123412324", "password_confirmation": "123412234"}' http://localhost:3000/v1/users` but see in my Rails server that I get this error:

``` bash
Started POST "/v1/users" for 127.0.0.1 at 2015-08-20 11:00:58 -0700
Processing by V1::UsersController#create as JSON
  Parameters: {"username"=>"testuser", "email"=>"test@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}
Completed 400 Bad Request in 1ms

ActionController::ParameterMissing (param is missing or the value is empty: user):
  app/controllers/v1/users_controller.rb:20:in `user_params'
  app/controllers/v1/users_controller.rb:8:in `create'
```

So, I then tried this command: `
curl -X POST -H "Content-Type: application/json" -d '{ "user": {"username": "testuser", "email": "test@example.com", "password": "123412324", "password_confirmation": "123412234"} }' http://localhost:3000/v1/users`

And this was returned:: `{"error":"translation missing: en.user_create_error"}`.

If I look in my Rails server I see this: 

``` bash
Started POST "/v1/users" for 127.0.0.1 at 2015-08-20 11:08:09 -0700
Processing by V1::UsersController#create as JSON
  Parameters: {"user"=>{"username"=>"testuser", "email"=>"test@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
   (0.1ms)  begin transaction
  User Exists (0.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'test@example.com' LIMIT 1
   (0.0ms)  rollback transaction
Completed 422 Unprocessable Entity in 66ms (Views: 0.1ms | ActiveRecord: 0.2ms)
```

So, any help on the default way to setup requests to the API would be much appreciated!

If you just want to comment here how to do it I can make the necessary Pull Request.  Thanks!

**Comment by Abundnce10** [comment]
Nevermind, I'm an idoit and didn't realize that I incorrectly typed the `password` and `password_confirmation` fields.  I can now successfully create a User through the API.  I work on the other routes and assuming I can do everything just fine I'll work on a PR for the README with example `curl` commands.

**Comment by andreamazz** [comment]
:+1:
