### ISSUE TITLE
Create Session

### ISSUE THREAD

**Issue by tsnevillecom** [FancyPixel/small-rails#5]
I'm getting Completed 422 Unprocessable Entity when I copy/paste the curl for sessions#create. I have not altered any code. Creating the user worked, but I cannot use cURL or Postman to create the session. Any idea?

The error returned by json is:
{
    "error": "translation missing: en.sessions_controller.invalid_login_attempt"
}

I noticed that the curl url is http://localhost:3000/v1/users, I've tried login instead of users, and it still errors.

**Comment by andrewheekin** [comment]
@tsnevillecom Same error here. Any ideas on a fix?

**Comment by andreamazz** [comment]
Hi all. The correct path is `v1/login`, I updated the readme.  
Starting from a fresh clone:

``` sh
bundle
rake db:create
rake db:migrate
rails runner "User.create(username: 'admin', email: 'admin@example.com', password: 'password')"
rails s

curl -X POST -H "Content-Type: application/json" -d '{"email": "admin@example.com", "password": "password"}' http://localhost:3000/v1/login
```

**Comment by andrewheekin** [comment]
Excellent, works for me! I had the wrong payload json (was using the create user payload instead of login payload)

**Comment by andreamazz** [comment]
Ace :+1:
